#pragma once
#include "../OdinMath/OdinMath.h"
#include "AABB3.h"
#include "AABB2.h"
#include "Sphere.h"
#include "Circle.h"
#include "Seg3.h"
#include "Seg2.h"
#include "Plane3.h"
#include "Plane2.h"
#include "Ray3.h"
#include "Ray2.h"
#include "OBB3.h"

#include "AABB2PointDistance.h"
#include "AABB2PointIntersection.h"